### ISSUE TITLE
Audio not working on firefox

### ISSUE THREAD

**Issue by j1m-ryan** [TomC17/Mohidoi#2]
![image](https://user-images.githubusercontent.com/20595836/235349768-3c9ae00d-18c2-4f85-bd0d-bdbe96739b95.png)
Audio won't play for me on firefox, not sure why beyond this error. Works on chrome

**Comment by Metagawa** [comment]
Should be fixed in latest version thanks to a voice engine replacement. If voices still do not play it is due to individual browser settings like disabled javascript or disabling the webaudio in firefox.

**Comment by j1m-ryan** [comment]
yeah its working now
